# Generated by Django 3.2.4 on 2021-07-17 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Take_attendance',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.employee')),
            ],
        ),
    ]
