# Generated by Django 3.2.4 on 2021-07-17 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_take_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='take_attendance',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
