# Generated by Django 3.2.4 on 2021-07-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_take_attendance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='take_attendance',
            name='status',
            field=models.CharField(default='', max_length=10),
        ),
    ]
