# Generated by Django 3.2.4 on 2021-07-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_alter_take_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='take_attendance',
            name='attendance_date',
            field=models.CharField(default='', max_length=10),
        ),
    ]
