# Generated by Django 3.2.9 on 2021-11-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20210722_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='university_roll_no',
            field=models.CharField(default='', max_length=13, unique=True),
            preserve_default=False,
        ),
    ]
