# Generated by Django 3.2.9 on 2021-11-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_auto_20211121_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
