# Generated by Django 3.2.9 on 2021-11-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_student_student_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='take_attendance',
            name='university_roll',
            field=models.CharField(default='', max_length=10),
        ),
    ]
