# Generated by Django 3.2.9 on 2021-12-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_take_attendance_university_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='take_attendance',
            name='section',
            field=models.CharField(default='', max_length=2),
        ),
    ]
